namespace: "spatiumcepa"
name: "platform"
version: "0.1.0"
readme: "README.md"
authors:
  - "Nicholas Kiraly <kiraly.nicholas@gmail.com>"
dependencies: []
license:
  - "BSD-2-Clause"
tags:
  - platform
repository: "https://github.com/spatium-cepa/ansible-collection-spatiumcepa-platform"
